### ISSUE TITLE
Connection to SAP HANA failed - wrong provider for this platform

### ISSUE THREAD

**Issue by i325814** [SAP/sap-hana-driver-for-sqltools#117]
Hi guys,
I would like to use "SAP HANA Driver for SQLTools" in Windows 10 but I am getting an error when I try to setup a connection.
I have got Hana started locally in Docker and when I setup a connection and press "TEST CONNECTION" I am getting the following error "**Running the contributed command: 'sqltools.testConnection' failed**" and the log messages:

```log
[1614092126771] INFO  (ext): EXECUTING COMMAND => sqltools.testConnection
[1614092126771] INFO  (ls): REQUEST RECEIVED => connection/TestConnectionRequest
['driver:saphana:error'] Connection to SAP HANA failed Error: Connection failed (RTE:[1000013] wrong provider for this platform (localhost:30041))
```

I wonder if it something specific for Windows because my colleague runs the same setup under Ubuntu and it works for him.

I had a look at previous issue: <https://github.com/SAP/sap-hana-driver-for-sqltools/issues/66> and I ran provided code (test.js) to check the connection.

My connection JSON from VSCode:

```json
{
    "connectionTimeout": 30,
    "hanaOptions": {
      "encrypt": true,
      "sslValidateCertificate": false,
      "sslCryptoProvider": "openssl"
    },
    "previewLimit": 50,
    "driver": "SAPHana",
    "name": "HANA Cloud Local Container",
    "group": "HANA Cloud",
    "server": "localhost",
    "port": 30041,
    "database": "SYSTEM",
    "username": "SYSTEM",
    "password": "Manager1"
  }
```

The connection was successful when I executed (`test.js`) with the following `settings` (`sslCryptoProvider` was commented out):

```js
const settings = {
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": true,
                "sslValidateCertificate": false,
                // "sslCryptoProvider": "openssl",
                // "key": "xxx"
            },
            "previewLimit": 50,
            "driver": "SAPHana",
            "name": "HANA Cloud Local Container",
            "server": "localhost",
            "port": 30041, 
            "database": "SYSTEM",
            "username": "SYSTEM",
            "password": "Manager1"
        }]
}
```

and failed with this one:

```js
const settings = {
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": true,
                "sslValidateCertificate": false,
                "sslCryptoProvider": "openssl",
                // "key": "xxx"
            },
            "previewLimit": 50,
            "driver": "SAPHana",
            "name": "HANA Cloud Local Container",
            "server": "localhost",
            "port": 30041, 
            "database": "SYSTEM",
            "username": "SYSTEM",
            "password": "Manager1"
        }]
}
```

The error log:
```log
C:\Users\i325814\playground\hana-cloud-driver>node test
Connection to SAP HANA failed Error: Connection failed (RTE:[1000013] wrong provider for this platform (localhost:30041))
C:\Users\i325814\playground\hana-cloud-driver\node_modules\@sap\hana-client\lib\index.js:52
        ldb.__runCallbacks();
            ^

Error: Connection failed (RTE:[1000013] wrong provider for this platform (localhost:30041))
    at Socket.<anonymous> (C:\Users\i325814\playground\hana-cloud-driver\node_modules\@sap\hana-client\lib\index.js:52:13)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: -10709,
  sqlState: ''
}
```

```bash
C:\>node --version
v12.19.0
```

```bash
C:\>openssl version
OpenSSL 1.1.1i  8 Dec 2020
```
Could you please give me a hand with this?

Cheers,
Artur

**Comment by i325814** [comment]
I found the answer here: https://blogs.sap.com/2020/04/14/secure-connection-from-hdbsql-to-sap-hana-cloud/
HDBSQL on Windows uses mscrypto (not openssl) and the default Windows certificate store. I reckon HDBSQL uses Hana Client under the hood so I did not have to specify sslCryptoProvider at whole.

**Comment by offer8** [comment]
Thanks for the issue and the clarification!
