### ISSUE TITLE
Errors when trying to generate insert query, or show table records

### ISSUE THREAD

**Issue by gman77** [SAP/sap-hana-driver-for-sqltools#137]
Thank you for this tool.

I'm using this tool to connect to an MTA hana hdi-shared.
I am able to connect successfully to the database, however of the option on right clicking the table names in the connections of sql tools only the "Describe Table" is working.

Using Sqltools 0.23.0
SAP Hana Driver for SQLTools 0.23.0
Running on Mac Big Sur 11.2.3

Included are the errors:

[2021-03-31 16:46:00.126] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
[2021-03-31 16:46:01.148] [exthost] [error] Error: Request connection/GetChildrenForTreeItemRequest failed unexpectedly without providing any details.
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:111820
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112227
    at Immediate.<anonymous> (/Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112769)
    at processImmediate (internal/timers.js:456:21) sqltools.getChildrenForTreeItem
[2021-03-31 16:46:02.005] [exthost] [error] Error: Request connection/GetChildrenForTreeItemRequest failed unexpectedly without providing any details.
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:111820
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112227
    at Immediate.<anonymous> (/Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112769)
    at processImmediate (internal/timers.js:456:21) sqltools.getChildrenForTreeItem
[2021-03-31 16:46:10.234] [exthost] [error] Error: Request connection/GetChildrenForTreeItemRequest failed unexpectedly without providing any details.
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:111820
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112227
    at Immediate.<anonymous> (/Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112769)
    at processImmediate (internal/timers.js:456:21) sqltools.getChildrenForTreeItem
[2021-03-31 16:46:10.234] [exthost] [error] Error: Running the contributed command: 'sqltools.getChildrenForTreeItem' failed.
    at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106930)
    at generateInsertQueryHandler (/Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:22:478092)
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:22:12977
    at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106762) sqltools.generateInsertQuery
[2021-03-31 16:49:19.344] [exthost] [error] Error: Request connection/GetChildrenForTreeItemRequest failed unexpectedly without providing any details.
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:111820
    at /Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112227
    at Immediate.<anonymous> (/Users/i1/.vscode/extensions/mtxr.sqltools-0.23.0/dist/extension.js:16:112769)
    at processImmediate (internal/timers.js:456:21) sqltools.getChildrenForTreeItem

**Comment by draschke** [comment]
_I am able to connect successfully to the database, however of the option on right clicking the table names in the connections of sql tools only the "Describe Table" is working._
Same issue.
And I miss an option to filter for tables! We do have a lot of tables.

The query selection works only if I open "New SQL File" and leverage an own select statement.

SAP HANA XSA 
SQLTools v0.23.0
SAP HANA Driver for SQLTools v0.2.1
